# Default values for ranger-usersync.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


image:
  repository: avs-alatau/ranger-usersync-k8s
  pullPolicy: Always
  tag: "2.4.0"


imagePullSecrets: []
nameOverride: "ranger-usersync"
fullnameOverride: "ranger-usersync"


serviceAccount:
  create: false
  annotations: {}
  name: ""


podAnnotations: {}


podSecurityContext: {}


securityContext: {}


service:
  type: ClusterIP
  port: 5151


ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ranger-usersync.dev.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


ranger_usersync_conf:
  ADMIN_PASSWORD: "ADMIN_PASSWORD"
  ADMIN_USERNAME: "ADMIN_USERNAME"
  keyadmin_password: "keyadmin_password"
  rangerUsersync_password: "rangerUsersync_password"
  ranger_local_pass: "ranger_local_pass"
  ranger_db_host: "ranger_db_host"
  ranger_scheduler_enabled: "true"
  ranger_ldap_ad_domain: "ranger_ldap_ad_domain"
  ldap_domen: "dev.local"
  ldap_user: "user_test"
  ldap_port: 389
  ranger_ldap_ad_base_dn: "DC=dev,DC=local"
  ranger_ldap_ad_bind_dn: "CN=ADMIN_USERNAME,ldap_user_dn"
  ranger_ldap_ad_referral: "follow"
  ranger_ldap_ad_user_searchfilter: "(sAMAccountName={0})"
  ranger_supportedcomponents: "hdfs,yarn,hive,knox,ozone,tag,kafka"
  ranger_admin_cookie_name: "RANGERADMINSESSIONID"
  java_home: "/usr/lib/jvm/java-8-openjdk-amd64"
  hadoop_home: "/etc/hadoop-default"
  ranger_usersync_sleeptimeinmillisbetweensynccycle: 3600000
  ranger_usersync_port: 5151
  ldap_host: "ldap_host"
  ranger_admin_host: "ranger_admin_host"
  ranger_ui_port: ranger_ui_port
  ranger_usersync_group_based_role_assignment_rules: "ranger_usersync_group_based_role_assignment_rules"
  ranger_usersync_group_memberattributename: "ranger_usersync_group_memberattributename"
  ranger_usersync_group_nameattribute: "ranger_usersync_group_nameattribute"
  ranger_usersync_group_objectclass: "ranger_usersync_group_objectclass"
  ranger_usersync_group_searchfilter: "ranger_usersync_group_searchfilter"
  ranger_usersync_group_searchscope: "ranger_usersync_group_searchscope"
  ranger_usersync_ldap_binddn: "ranger_usersync_ldap_binddn"
  ranger_usersync_ldap_deltasync: "ranger_usersync_ldap_deltasync"
  ranger_usersync_ldap_referral: "ranger_usersync_ldap_referral"
  ranger_usersync_ldap_searchBase: "ranger_usersync_ldap_searchBase"
  ranger_usersync_ldap_user_groupnameattribute: "ranger_usersync_ldap_user_groupnameattribute"
  ranger_usersync_ldap_user_objectclass: "ranger_usersync_ldap_user_objectclass"
  ranger_usersync_ldap_user_searchbase: "ranger_usersync_ldap_user_searchbase"
  ranger_usersync_ldap_user_searchfilter: "ranger_usersync_ldap_user_searchfilter"
  ranger_usersync_ldap_user_searchscope: "ranger_usersync_ldap_user_searchscope"
  ranger_usersync_sync_group_search_base: "ranger_usersync_sync_group_search_base"
  ranger_usersync_sync_source: "ranger_usersync_sync_source"


resources:
  limits:
    cpu: 4
    memory: 8Gi
  requests:
    cpu: 2
    memory: 4Gi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


nodeSelector: {}


tolerations: []


affinity: {}


script:

