apiVersion: v1
kind: ConfigMap
metadata:
  name: "xml-configmap"
  labels:
    app.kubernetes.io/name: {{ include "helm-chart.name" . }}
    helm.sh/chart: {{ include "helm-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  ranger-ugsync-site.xml: |
    <configuration>
            <property>
                    <name>ranger_base_dir</name>
                    <value>/etc/ranger/</value>
            </property>
            <property>
                    <name>ranger.usersync.credstore.filename</name>
                    <value>/etc/ranger/usersync/conf/rangerusersync.jceks</value>
            </property>
            <property>
                    <name>ranger.usersync.enabled</name>
                    <value>false</value>
            </property>
            <property>
                    <name>ranger.usersync.group.memberattributename</name>
                    <value>member</value>
            </property>
            <property>
                    <name>ranger.usersync.group.nameattribute</name>
                    <value>cn</value>
            </property>
            <property>
                    <name>ranger.usersync.group.objectclass</name>
                    <value>posixGroup</value>
            </property>
            <property>
                    <name>ranger.usersync.group.searchbase</name>
                    <value>cn=admin,dc=example,dc=org</value>
            </property>
            <property>
                    <name>ranger.usersync.group.searchenabled</name>
                    <value>true</value>
            </property>
            <property>
                    <name>ranger.usersync.group.searchfilter</name>
                    <value>cn=*</value>
            </property>
            <property>
                    <name>ranger.usersync.group.searchscope</name>
                    <value>sub</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.binddn</name>
                    <value>cn=sub"admin",cn=admin,dc=example,dc=org</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.groupname.caseconversion</name>
                    <value>none</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.ldapbindpassword</name>
                    <value>Not@SecurePassw0rd</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.searchBase</name>
                    <value>cn=admin,dc=example,dc=org</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.url</name>
                    <value>ldap://openldap.openldap.svc.cluster.local:389</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.deltasync</name>
                    <value>true</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.user.groupnameattribute</name>
                    <value>memberof,ismemberof</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.user.nameattribute</name>
                    <value>cn</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.user.objectclass</name>
                    <value>posixAccount</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.user.searchbase</name>
                    <value>cn=admin,dc=example,dc=org</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.user.searchfilter</name>
                    <value>cn=*</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.user.searchscope</name>
                    <value>sub</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.username.caseconversion</name>
                    <value>none</value>
            </property>
            <property>
                    <name>ranger.usersync.logdir</name>
                    <value>logs</value>
            </property>
            <property>
                    <name>ranger.usersync.pagedresultsenabled</name>
                    <value />
            </property>
            <property>
                    <name>ranger.usersync.pagedresultssize</name>
                    <value />
            </property>
            <property>
                    <name>ranger.usersync.passwordvalidator.path</name>
                    <value>./native/credValidator.uexe</value>
            </property>
            <property>
                    <name>ranger.usersync.policymanager.baseURL</name>
                    <value>http://ranger-admin-admin-svc:6080</value>
            </property>
            <property>
                    <name>ranger.usersync.policymanager.maxrecordsperapicall</name>
                    <value>1000</value>
            </property>
            <property>
                    <name>ranger.usersync.policymanager.mockrun</name>
                    <value>false</value>
            </property>
            <property>
                    <name>ranger.usersync.port</name>
                    <value>5151</value>
            </property>
            <property>
                    <name>ranger.usersync.sink.impl.class</name>
                    <value>org.apache.ranger.unixusersync.process.PolicyMgrUserGroupBuilder</value>
            </property>
            <property>
                    <name>ranger.usersync.sleeptimeinmillisbetweensynccycle</name>
                    <value>900000</value>
            </property>
            <property>
                    <name>ranger.usersync.source.impl.class</name>
                    <value>org.apache.ranger.ldapusersync.process.LdapUserGroupBuilder</value>
            </property>
            <property>
                    <name>ranger.usersync.ssl</name>
                    <value>true</value>
            </property>
            <property>
                    <name>ranger.usersync.unix.minUserId</name>
                    <value>1000</value>
            </property>
            <property>
                    <name>ranger.usersync.unix.minGroupId</name>
                    <value>500</value>
            </property>
            <property>
                    <name>ranger.usersync.keystore.file</name>
                    <value>/etc/ranger/usersync/conf/cert/unixauthservice.jks</value>
            </property>
            <property>
                    <name>ranger.usersync.truststore.file</name>
                    <value />
            </property>
            <property>
                    <name>ranger.usersync.policymgr.username</name>
                    <value>rangerusersync</value>
            </property>
            <property>
                    <name>ranger.usersync.policymgr.alias</name>
                    <value>ranger.usersync.policymgr.password</value>
            </property>
            <property>
                    <name>ranger.usersync.policymgr.keystore</name>
                    <value>/etc/ranger/usersync/conf/rangerusersync.jceks</value>
            </property>
            <property>
                    <name>ranger.usersync.sync.source</name>
                    <value>ldap</value>
            </property>
            <property>
                    <name>ranger.usersync.ldap.referral</name>
                    <value>follow</value>
            </property>
            <property>
                    <name>ranger.usersync.kerberos.principal</name>
                    <value />
            </property>
            <property>
                    <name>ranger.usersync.kerberos.keytab</name>
                    <value />
            </property>
            <property>
          <name>ranger.usersync.keystore.password</name>
          <value>_</value>
        </property>
        <property>
          <name>ranger.usersync.truststore.password</name>
          <value>_</value>
        </property>
        <property>
          <name>ranger.usersync.role.assignment.list.delimiter</name>
              <value>&amp;</value>
            </property>
            <property>
          <name>ranger.usersync.users.groups.assignment.list.delimiter</name>
          <value>:</value>
            </property>
            <property>
          <name>ranger.usersync.username.groupname.assignment.list.delimiter</name>
          <value>,</value>
            </property>
        <property>
              <name>ranger.usersync.group.based.role.assignment.rules</name>
          <value />
        </property>
        <property>
                    <name>ranger.usersync.dest.ranger.session.cookie.name</name>
                    <value>RANGERADMINSESSIONID</value>
            </property>
        <property>
                    <name>ranger.usersync.metrics.enabled</name>
                    <value>true</value>
        </property>
        <property>
                    <name>ranger.usersync.metrics.filepath</name>
                    <value>logs</value>
        </property>
        <property>
                    <name>ranger.usersync.metrics.frequencytimeinmillis</name>
                    <value>10000</value>
        </property>
        <property>
                    <name>ranger.usersync.metrics.filename</name>
                    <value>ranger_usersync_metric.json</value>
        </property>


            <property>
                    <name>ranger.service.name</name>
                    <value>ranger-ugsync</value>
            </property>
            <property>
                    <name>ranger-ugsync.server.ha.enabled</name>
                    <value>false</value>
            </property>
            <property>
                    <name>ranger-ugsync.server.ha.zookeeper.zkroot</name>
                    <value>/ranger-ugsync</value>
            </property>
            <property>
                    <name>ranger-ugsync.server.ha.zookeeper.connect</name>
                    <value />
            </property>
            <property>
                    <name>ranger-ugsync.server.ha.ids</name>
                    <value>id1,id2</value>
            </property>
            <property>
                    <name>ranger-ugsync.server.ha.address.id1</name>
                    <value />
            </property>
            <property>
                    <name>ranger-ugsync.server.ha.address.id2</name>
                    <value />
            </property>
            <property>
                    <name>ranger-ugsync.server.ha.zookeeper.retry.sleeptime.ms</name>
                    <value>1000</value>
            </property>
            <property>
                    <name>ranger-ugsync.server.ha.zookeeper.session.timeout.ms</name>
                    <value>20000</value>
            </property>
            <property>
                    <name>ranger-ugsync.server.ha.zookeeper.num.retries</name>
                    <value>3</value>
            </property>
            <property>
                    <name>ranger-ugsync.server.ha.zookeeper.acl</name>
                    <value />
            </property>
            <property>
                    <name>ranger-ugsync.server.ha.zookeeper.auth</name>
                    <value />
            </property>
            <property>
                    <name>ranger-ugsync.server.ha.http.port</name>
                    <value />
            </property>
            <property>
                    <name>ranger-ugsync.server.ha.https.port</name>
                    <value />
            </property>
    </configuration>