apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "helm-chart.name" . }}
    helm.sh/chart: {{ include "helm-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  install.properties: |
    ranger_base_dir = /etc/ranger
    POLICY_MGR_URL = http://{{ .Values.ranger_usersync_conf.ranger_admin_host }}:{{ .Values.ranger_usersync_conf.ranger_ui_port }}
    SYNC_SOURCE = {{ .Values.ranger_usersync_conf.ranger_usersync_sync_source }}
    MIN_UNIX_USER_ID_TO_SYNC = 1000
    MIN_UNIX_GROUP_ID_TO_SYNC = 500
    SYNC_INTERVAL = 15
    unix_user=ranger
    unix_group=ranger
    rangerUsersync_password={{ .Values.ranger_usersync_conf.rangerUsersync_password }}
    usersync_principal=
    usersync_keytab=
    hadoop_conf={{ .Values.ranger_usersync_conf.hadoop_home }}
    CRED_KEYSTORE_FILENAME=/etc/ranger/usersync/conf/rangerusersync.jceks
    AUTH_SSL_ENABLED=false
    AUTH_SSL_KEYSTORE_FILE=/etc/ranger/usersync/conf/cert/unixauthservice.jks
    AUTH_SSL_KEYSTORE_PASSWORD=XXXXXXX
    AUTH_SSL_TRUSTSTORE_FILE=
    AUTH_SSL_TRUSTSTORE_PASSWORD=
    ROLE_ASSIGNMENT_LIST_DELIMITER = &
    USERS_GROUPS_ASSIGNMENT_LIST_DELIMITER = :
    USERNAME_GROUPNAME_ASSIGNMENT_LIST_DELIMITER = ,
    GROUP_BASED_ROLE_ASSIGNMENT_RULES = {{ .Values.ranger_usersync_conf.ranger_usersync_group_based_role_assignment_rules }}
    SYNC_LDAP_URL = ldap://{{ .Values.ranger_usersync_conf.ldap_host }}:{{ .Values.ranger_usersync_conf.ldap_port }}
    SYNC_LDAP_BIND_DN =cn={{ .Values.ranger_usersync_conf.ADMIN_USERNAME }},{{ .Values.ranger_usersync_conf.ranger_usersync_sync_group_search_base }}
    SYNC_LDAP_BIND_PASSWORD ={{ .Values.ranger_usersync_conf.ADMIN_PASSWORD }}
    SYNC_LDAP_DELTASYNC = {{ .Values.ranger_usersync_conf.ranger_usersync_ldap_deltasync }}
    SYNC_LDAP_SEARCH_BASE ={{ .Values.ranger_usersync_conf.ranger_usersync_ldap_searchBase }}
    SYNC_LDAP_USER_SEARCH_BASE ={{ .Values.ranger_usersync_conf.ranger_usersync_ldap_user_searchbase }}
    SYNC_LDAP_USER_SEARCH_SCOPE = {{ .Values.ranger_usersync_conf.ranger_usersync_ldap_user_searchscope }}
    SYNC_LDAP_USER_OBJECT_CLASS = {{ .Values.ranger_usersync_conf.ranger_usersync_ldap_user_objectclass }}
    SYNC_LDAP_USER_SEARCH_FILTER ={{ .Values.ranger_usersync_conf.ranger_usersync_ldap_user_searchfilter }}
    SYNC_LDAP_USER_NAME_ATTRIBUTE = {{ .Values.ranger_usersync_conf.ranger_usersync_group_nameattribute }}
    SYNC_LDAP_USER_GROUP_NAME_ATTRIBUTE = {{ .Values.ranger_usersync_conf.ranger_usersync_ldap_user_groupnameattribute }}
    SYNC_LDAP_USERNAME_CASE_CONVERSION=none
    SYNC_LDAP_GROUPNAME_CASE_CONVERSION=none
    logdir=logs
    USERSYNC_PID_DIR_PATH={{ .Values.ranger_usersync_conf.ranger_usersync_pid_dir_path }}
    SYNC_GROUP_SEARCH_ENABLED=true
    SYNC_GROUP_USER_MAP_SYNC_ENABLED={{ .Values.ranger_usersync_conf.ranger_usersync_group_searchenabled }}
    SYNC_GROUP_SEARCH_BASE={{ .Values.ranger_usersync_conf.ranger_usersync_sync_group_search_base }}
    SYNC_GROUP_SEARCH_SCOPE={{ .Values.ranger_usersync_conf.ranger_usersync_group_searchscope }}
    SYNC_GROUP_OBJECT_CLASS={{ .Values.ranger_usersync_conf.ranger_usersync_group_objectclass }}
    SYNC_LDAP_GROUP_SEARCH_FILTER={{ .Values.ranger_usersync_conf.ranger_usersync_group_searchfilter }}
    SYNC_GROUP_NAME_ATTRIBUTE={{ .Values.ranger_usersync_conf.ranger_usersync_group_nameattribute }}
    SYNC_GROUP_MEMBER_ATTRIBUTE_NAME={{ .Values.ranger_usersync_conf.ranger_usersync_group_memberattributename }}
    SYNC_PAGED_RESULTS_ENABLED=
    SYNC_PAGED_RESULTS_SIZE=
    SYNC_LDAP_REFERRAL =follow
    JVM_METRICS_ENABLED=true
    JVM_METRICS_FILENAME=ranger_usersync_metric.json
    JVM_METRICS_FILEPATH=logs
    JVM_METRICS_FREQUENCY_TIME_IN_MILLIS=10000

